name: Test disk speed
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        base_image: https://github.com/radxa/rock-pi-s-images-released/releases/download/rock-pi-s-v20210924/rockpis_debian_buster_server_arm64_20210924_0412-gpt.img.gz
        cpu: cortex-a53
        image_additional_mb: 4096
        debug: false
        commands: |
          mount
          apt-get update && apt-get install -y time
          time dd if=/dev/zero of=test1 bs=102400 count=100
          time dd if=/dev/zero of=test1 bs=102400 count=100
          time dd if=/dev/zero of=test1 bs=102400 count=100
