name: Test expand GPT partition table
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'test-x86'
  pull_request:
  workflow_dispatch:

jobs:
  build-rock-pi-s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # pguyot/arm-runner-action@HEAD
        with:
          base_image: https://github.com/radxa/rock-pi-s-images-released/releases/download/rock-pi-s-v20210924/rockpis_debian_buster_server_arm64_20210924_0412-gpt.img.gz
          image_additional_mb: 2048
          cpu: cortex-a53
          commands: |
            test $(df -h --output=size / | tail -n 1) = '2.8G'
  build-armbian-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # pguyot/arm-runner-action@HEAD
        with:
          base_image: https://armbian.chi.auroradev.org/dl/uefi-x86/archive/Armbian_22.11.1_Uefi-x86_bullseye_current_5.15.80_minimal.img.xz
          bootpartition: ""
          rootpartition: 3
          image_additional_mb: 1024
          commands: |
            test $(df -h --output=size / | tail -n 1) = '4.0G'
